import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import { Roboto_Slab } from "next/font/google"; 
import {AppProviders} from "@/redux/store/provider";

import { Toaster } from "react-hot-toast";
import ToastBridge from "@/components/ToastBridge";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const grotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
  weight: ["400", "600"],
});

const robotoSlab = Roboto_Slab({ // ✅ NEW
  variable: "--font-roboto-slab",
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${grotesk.variable} ${robotoSlab.variable} antialiased`}
      >
        <AppProviders>
        <Navbar />
        {children}
        {/* for toast */}
         <ToastBridge/>
        <Toaster position="top-right" toastOptions={{duration:3000}} />
        <Footer/>
        </AppProviders>
      </body>
    </html>
  );
}
